### ISSUE TITLE
Issues from hackaton

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/Goliath#2]
Okay, I check the link you send us: https://www.bigcat.unimaas.nl/bridgedbconverter/ .
- [x] Make font of intro text larger (I cannot read it properly now). And/or put a white box behind it (and make text darker). The text I mean is: "Please copy paste your ID list.
The system will try to guess your id type. If it's not correct, please adjust accordingly."
And I would change this text to:

"Easy identifier mapping! Just copy paste your IDs (one per line) and select the database you want to map to. Goliath makes an initial guess for the database you are mapping from. If this guess is incorrect, you can adjust the convert from section accordingly."

- [x] Species iso Specie

- [ ] When I click download (and select one of the two options), I get a pop-up menu:
![image](https://user-images.githubusercontent.com/26277832/50374075-ad539b80-05e8-11e9-9237-2ba581890bb2.png)

I think some explanatory text here would really help :)..

- [x] Download gives me the syscode behind the ID; that makes the resulting tsv not directly compatible with Pathvisio etc... Would it be possible to include the header (to indicate from which database to which has been mapped?); or add 2 columns, one with the syscode of the original given IDs, one with the mapped ones?

![image](https://user-images.githubusercontent.com/26277832/50374090-e429b180-05e8-11e9-8ed8-772c9a1a6a56.png)

- [x] It seems to only work for the example given; I tried to map from wikidata to HMDB (List of IDs: Q4545703
Q27109160
Q4673297
Q413822
Q7098084)
That didn't work....

- [ ] Last, the background now implies the mapping is only useful for Gene/proteins.... I see Chemical mapping is possible as well, so adjusting the background (perhaps cut the background in 3 parts; left: DNA; middle: ID mapping (so no background; right: some chemicals)... And will the gene-variant mappings and interaction mappings also run from this website?

If you have more questions on what I said above, or want me to test again, don't hesitate to ask @nunogit  ;)

**Comment by nunogit** [comment]
Thanks @DeniseSl22. The popups are just for debug purposes, nothing more.

**Comment by Chris-Evelo** [comment]
I was wondering... 

Does it limit the options for what an ID can be from based on what you say it wants to go too? And the other way around if you really select what it is? Of course, some kinds of mappings do not make sense. Maybe there should be a crude selector as well? (I want to map: gene products, metabolites, reaction, variants) 

How compatible is this in usage with DAVID? 

I agree that the background should be less genetics only. And should not interfere with functionality in any sense (and ideally it should be CC0 or maybe, in this case, it is even better if we own it)

**Comment by DeniseSl22** [comment]
- [ ] Add DOIs + citation for source of data (for example Biomart states: Human genes (GRCh38.p12) Genome build).
- [ ] Should Gene-variant mappings be included?
- [ ] Add URLs (linkouts) as results (perhaps as separate column?)
- [ ] orthologous mapping (between species).
- [ ] Upload data as textfile (drag and drop, only tsv or txt files, one ID per line, no additional columns) or copy paste.

**Comment by Chris-Evelo** [comment]
1) Denise, do you mean the mapping (linkset) data used?
2) Gene-variant should probably be a dedicated service (so another instance), since this is likely a completely different audience with different needs, speaking in part a different language.
3) These URLS should ideally be background links to identifiers  provided as identifiers.orn (and n2t) shorthand. E.g. UniProt:P12345 See: 
https://docs.google.com/document/d/19byWkkBOaK3o4xwL1rbBNKNBRYZwPwLlIpR4eXcdru8/edit
4) orthologous mappings are normally not mappings but similarities between different species calculated from % identity and such. There are curated mappings available at dedicated sites, e,.g. Homologene. i think we should leave those there for now. Hardly our expertise. Also these sites are really dedicated to just that (other than ENSEMBL that has mappings as a side product)
5) Agree, but please make sure that the mechanisms that people are used to use (from DAVID) still work, including formats accepted there

**Comment by DeniseSl22** [comment]
1. Yes; I think people need to see which data is used for their mapping question. And if we upload a new mapping file to the webservice, their mappings can change (slightly), so it would be good to show them which files are behind the webservice for the mapping.
2. Mhh okay, then best to discuss that with Freddie.... So for now, Goliath should map between gene/protein databases, metabolite databases, and interaction databases?
3. I was more thinking of why users would like to perform mappings; for example: a mass-spec has been annotated with pubchem-compound IDs, but another tool needed for further data analysis needs HMDB iso Pubchem; if we would include a short version of the Syscodes that we use in the background, I would want to see that as a separate column (so people can still copy-past the results and use them directly, iso first removing the "pubchemc:" and "hmdb;").
4. Well, this depends on how you define mappings. If I would like to analyse a mouse transcriptomics dataset with the Human WikiPathways collection, I cannot use BridgeDb for that easily now... Goliath could be a solution for that, since the mappings between genes for one species is already in place.
5. I'll check the [website](https://david.ncifcrf.gov/), to see how they are letting people perform annotation. But if we also want to do mappings from name to identifier, a CSV file will not suffice for chemical compounds (which tend to have comma's in there from time to time)...

**Comment by nunogit** [comment]
@Chris-Evelo "Of course, some kinds of mappings do not make sense."  Only the compatible conversion are given on the options. If you select Affy and you want to convert to something incompatible that option will not even be there.

Regarding the ID's themselfs, if you put whatever and you say "I want to convert from Affy to SomethingElse" no conversion will be done since the ID's won't be found.

**Comment by nunogit** [comment]
@DeniseSl22 I am starting to work on this issue. I will probably create sub tasks from this one.
We should probably create a release goal though. What do you think? If we start adding too many things to the wish list we might never publish the website. What do you think?

**Comment by DeniseSl22** [comment]
@nunogit , yes, I'll make separate issues out of the points mentioned above. I think most are enhanchements, and therefore not directly needed for first release. I'm closing this issue.
