### ISSUE TITLE
Metabolite conversion does not work

### ISSUE THREAD

**Issue by fehrhart** [bridgedb/Goliath#4]
I tried to convert this small list of HMDB to InChI, and it does not work. Neither autodetect nor after selecting HMDB. I converted them succesfully with another tool, so the InChIs are available. 

HMDB00112
HMDB00295
HMDB00901
HMDB00935
HMDB01275
HMDB01877
HMDB13037

**Comment by nunogit** [comment]
Conversion from HMDB to InChI

**Comment by Chris-Evelo** [comment]
Did you try it with BridgeDb itself? And are the INCHIs visible on WikiPathways whenever you have a metabolite with one of these IDs

**Comment by fehrhart** [comment]
I tried conversion to InChI key - InChI is not offered in the converter. InChI key is visible on WikiPathways. I also tried some other conversions like from HMDB to ChEMBL and other identifiers but that also did not work. I therefore presumed that the whole metabolite conversion does not work.

**Comment by nunogit** [comment]
@Chris-Evelo @fehrhart 

I tried it on the webservice and it seems to be working. The bug is most likely @ Goliath:

curl -X GET --header 'Accept: */*' 'https://webservice.bridgedb.org/Human/xrefs/Ch/HMDB00112'

BTCSSZJGUNDROE-UHFFFAOYSA-N	InChIKey
116	Chemspider
16865	ChEBI
119	PubChem-compound
C00001337	KNApSAcK
56-12-2	CAS
LMFA01100039	LIPID MAPS
D00058	KEGG Drug
DTXSID6035106	EPA CompTox
C00334	KEGG Compound
HMDB00112	HMDB
CHEBI:16865	ChEBI
HMDB0000112	HMDB
Q210021	Wikidata

**Comment by nunogit** [comment]
@fehrhart  I just fixed Goliath. It's now working.

From

HMDB00112
HMDB00295
HMDB00901
HMDB00935
HMDB01275
HMDB01877
HMDB13037

I got

HMDB00112 | 16865 |  
HMDB00295 | 17659 |  
HMDB00901 | undefined |  
HMDB00935 | CHEBI:17200 |  
HMDB01275 | 15539 |  
HMDB01877 | CHEBI:39867 |  
HMDB13037 | 7981

**Comment by fehrhart** [comment]
Thanks!
I just tried, so I can confirm it works :)

**Comment by Chris-Evelo** [comment]
But? Is that literally the result you got @nunogit? Why are some just identifiers without the resource mentioned while others are regular short IDs?

**Comment by nunogit** [comment]
@Chris-Evelo that's a good question, and that's why I opened another ticket to solve this.

Goliath is only picking the first result for each converstion, but the fact is that you can get more than one result for chebi (and probably for other it types)

In chebi you allways get as result at least the id and the id with prefix chebi:
It also happens that you get more than one id (different numbers) for one metabolite.

Wrapping up:  we need to decide if we want to keep both formats (if  I understand it right) id and chebi:id. 
And we need to decide what to do when a coversion has more than 1 result.

Please look at #6 and it will be more clear.

**Comment by egonw** [comment]
@Chris-Evelo, all, there are two factors involved in that (possibly more):

1. ChEBI identifiers comes in two flavors with and without prefix, and for interoperability, BridgeDb gives both (@nunogit, Goliath should compensate for that, and provide only one. Also applies to HMDB identifiers, which also comes in two flavors)
2. ChEBI has primary and secondary identifiers (like deprecated identifiers). However, BridgeDb currently does not have an API to let you know which is what (feature is planned)

**Comment by nunogit** [comment]
@egonw 1. clear! Although, I am not sure that logic should be exclusively in goliath. Maybe we should have something like a "preferred id format",similar to a deprecated tag. Goliath would pick the preferred one. 

2. That would definitely be a good improvement


We should move this discussion to #6

**Comment by Chris-Evelo** [comment]
Yes, but we also need to decide what the preferred output is. ShortIDs (resource:id) or just IDs. I think that that should be configurable. I think that for now providing just the ID would be fine. Not many tools can deal with ShortIDs yet (actually PathVisio can not handle it yet, I think?).

**Comment by nunogit** [comment]
@Chris-Evelo, so we should output eg: 1234 rather than CHEBI:1234.

Are there other target id types where this happens?

**Comment by egonw** [comment]
@Chris-Evelo, BridgeDb does not have compact identifier support yet.

**Comment by nunogit** [comment]
I am bit lost @egonw, what do you call CHEBI:1234 or just 1234? what is compact identifier support?

**Comment by egonw** [comment]
@nunogit, see https://www.nature.com/articles/sdata201829

**Comment by DeniseSl22** [comment]
Hi @nunogit ,

I would prefer to use CHEBI:1234 ; simply because then people see where the identifier comes from with more ease. HMDB also includes their database name in the identifier, and Ensembl does this too (even with a code to see which species the ID belongs too). And Pathvisio can handle both ChEBIs (so CHEBI:1234 and 1234). About the secondary IDs: it would be great if we could do such a mapping at some point (as well as for outdated IDs from other databases), however these are very specific use cases, so I wouldn't bother with it now. Therefore, I believe the correct format for metabolite IDs should be:

- [ ] ChEBI   CHEBI:1234
- [ ] HMDB HMDB0012345 (so with a length of 11, not 9, that was the old structure of the ID).
- [ ] Inchi+InchiKey Not sure about these, what do you think @egonw ... At Wikidata the Inchi is not given with the prefix "InChI=", at wikipedia this is given (because they add the InchiKey under the same database (and given a prefix "Key"); we do not do that in BridgeDb right?).
- [ ] please add other specific examples if needed.

**Comment by Chris-Evelo** [comment]
IDs like CHEBI:12345 are what we call compact IDs. And we do advocate those being used. However, the concept is rather new and not many tools support them as input. That is why I suggested to have bare IDs as the default but allow users to select that they want compact IDs. Note that you can also give these as links (identifiers.org/resource:ID or n2t.net/resource:ID) (the first is preferred, because in Europe and an ELIXIR RIR itself)

**Comment by Chris-Evelo** [comment]
@egonw what do you think? Should we build compact identifier support in BridgeDb and then use that on Goliath with an API option sitch? Or should we just let Goliath do that itself?  The first would be less error prone I suppose

**Comment by DeniseSl22** [comment]
I'm closing this issue, since the metabolite mapping is working, and creating a new issue (since this conversation is different compared to #6 ).

**Comment by nunogit** [comment]
@egonw @Chris-Evelo the name, in my perspective is not very happy. 

Call CHEBI:12345 a compact identifier, compared to 12345...

**Comment by Chris-Evelo** [comment]
LOL, no, but that is not what you should compare it too. 12345 is not a complete semantic identifier at all, if you read that in a paper you would not know what it was about, at least not without further information. Something like: https://www.uniprot.org/uniprot/P12345 is a complete identifier  But then Uniprot:P12345 is more compact and also more persistent. Of course, you need resolution services, but that is what identifiers.org and n2t.net offer

**Comment by egonw** [comment]
OK, did not want to further complicate things, but CHEBI:12345 is not the compact identifiers... the namespace is in fact lower case, so the compact identifier would be chebi:12345 ...

**Comment by egonw** [comment]
OK, ignore that... https://n2t.net/CHEBI:12345 works fine... it seems identifers.org is just wrong in the MIRIAM registry...

**Comment by Chris-Evelo** [comment]
I think that was a CHEBI problem. I could get anything from there a few minute ago. Not getting there via identifiers.org works fine even with CHEBI in capitals

**Comment by egonw** [comment]
Yes, the proper resolving of the compact identifier for identifiers.org is http://identifiers.org/CHEBI:12345 and that works fine indeed.

**Comment by DeniseSl22** [comment]
Could we stop discussing this here, and move to #11 ?
